// Code generated for beachrockhotel service
// © beachrockhotel 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/beachrockhotel/rocket-factory/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// CancelOrderByUUID provides a mock function with given fields: ctx, orderUUID
func (_m *OrderRepository) CancelOrderByUUID(ctx context.Context, orderUUID string) (struct{}, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrderByUUID")
	}

	var r0 struct{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (struct{}, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) struct{}); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(struct{})
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_CancelOrderByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrderByUUID'
type OrderRepository_CancelOrderByUUID_Call struct {
	*mock.Call
}

// CancelOrderByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *OrderRepository_Expecter) CancelOrderByUUID(ctx interface{}, orderUUID interface{}) *OrderRepository_CancelOrderByUUID_Call {
	return &OrderRepository_CancelOrderByUUID_Call{Call: _e.mock.On("CancelOrderByUUID", ctx, orderUUID)}
}

func (_c *OrderRepository_CancelOrderByUUID_Call) Run(run func(ctx context.Context, orderUUID string)) *OrderRepository_CancelOrderByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_CancelOrderByUUID_Call) Return(_a0 struct{}, _a1 error) *OrderRepository_CancelOrderByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_CancelOrderByUUID_Call) RunAndReturn(run func(context.Context, string) (struct{}, error)) *OrderRepository_CancelOrderByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *OrderRepository) CreateOrder(ctx context.Context, order model.CreateOrderParams) (model.OrderDTO, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 model.OrderDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrderParams) (model.OrderDTO, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrderParams) model.OrderDTO); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Get(0).(model.OrderDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateOrderParams) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.CreateOrderParams
func (_e *OrderRepository_Expecter) CreateOrder(ctx interface{}, order interface{}) *OrderRepository_CreateOrder_Call {
	return &OrderRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *OrderRepository_CreateOrder_Call) Run(run func(ctx context.Context, order model.CreateOrderParams)) *OrderRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateOrderParams))
	})
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) Return(_a0 model.OrderDTO, _a1 error) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) RunAndReturn(run func(context.Context, model.CreateOrderParams) (model.OrderDTO, error)) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByUUID provides a mock function with given fields: ctx, orderUUID
func (_m *OrderRepository) GetOrderByUUID(ctx context.Context, orderUUID string) (model.OrderDTO, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByUUID")
	}

	var r0 model.OrderDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.OrderDTO, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.OrderDTO); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(model.OrderDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_GetOrderByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByUUID'
type OrderRepository_GetOrderByUUID_Call struct {
	*mock.Call
}

// GetOrderByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *OrderRepository_Expecter) GetOrderByUUID(ctx interface{}, orderUUID interface{}) *OrderRepository_GetOrderByUUID_Call {
	return &OrderRepository_GetOrderByUUID_Call{Call: _e.mock.On("GetOrderByUUID", ctx, orderUUID)}
}

func (_c *OrderRepository_GetOrderByUUID_Call) Run(run func(ctx context.Context, orderUUID string)) *OrderRepository_GetOrderByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_GetOrderByUUID_Call) Return(_a0 model.OrderDTO, _a1 error) *OrderRepository_GetOrderByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetOrderByUUID_Call) RunAndReturn(run func(context.Context, string) (model.OrderDTO, error)) *OrderRepository_GetOrderByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function with given fields: ctx, transactionUUID, paymentMethod, orderUUID
func (_m *OrderRepository) PayOrder(ctx context.Context, transactionUUID string, paymentMethod string, orderUUID string) (string, error) {
	ret := _m.Called(ctx, transactionUUID, paymentMethod, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, transactionUUID, paymentMethod, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, transactionUUID, paymentMethod, orderUUID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, transactionUUID, paymentMethod, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderRepository_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - transactionUUID string
//   - paymentMethod string
//   - orderUUID string
func (_e *OrderRepository_Expecter) PayOrder(ctx interface{}, transactionUUID interface{}, paymentMethod interface{}, orderUUID interface{}) *OrderRepository_PayOrder_Call {
	return &OrderRepository_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, transactionUUID, paymentMethod, orderUUID)}
}

func (_c *OrderRepository_PayOrder_Call) Run(run func(ctx context.Context, transactionUUID string, paymentMethod string, orderUUID string)) *OrderRepository_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *OrderRepository_PayOrder_Call) Return(_a0 string, _a1 error) *OrderRepository_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_PayOrder_Call) RunAndReturn(run func(context.Context, string, string, string) (string, error)) *OrderRepository_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
