// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOrder implements CancelOrder operation.
//
// Cancel an unpaid order by UUID.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) CancelOrder(ctx context.Context, params CancelOrderParams) (r CancelOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrder implements CreateOrder operation.
//
// Create order based on the details selected by user.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderRequest) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePayment implements CreatePayment operation.
//
// Makes payment for the created order.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) CreatePayment(ctx context.Context, req *PayOrderRequest, params CreatePaymentParams) (r CreatePaymentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrder implements GetOrder operation.
//
// Get order by UUID.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrder(ctx context.Context, params GetOrderParams) (r GetOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
