// Code generated for beachrockhotel service
// © beachrockhotel 2026.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/beachrockhotel/rocket-factory/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrderByUUID provides a mock function with given fields: ctx, orderUUID
func (_m *OrderService) CancelOrderByUUID(ctx context.Context, orderUUID string) (struct{}, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrderByUUID")
	}

	var r0 struct{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (struct{}, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) struct{}); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(struct{})
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_CancelOrderByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrderByUUID'
type OrderService_CancelOrderByUUID_Call struct {
	*mock.Call
}

// CancelOrderByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *OrderService_Expecter) CancelOrderByUUID(ctx interface{}, orderUUID interface{}) *OrderService_CancelOrderByUUID_Call {
	return &OrderService_CancelOrderByUUID_Call{Call: _e.mock.On("CancelOrderByUUID", ctx, orderUUID)}
}

func (_c *OrderService_CancelOrderByUUID_Call) Run(run func(ctx context.Context, orderUUID string)) *OrderService_CancelOrderByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_CancelOrderByUUID_Call) Return(_a0 struct{}, _a1 error) *OrderService_CancelOrderByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_CancelOrderByUUID_Call) RunAndReturn(run func(context.Context, string) (struct{}, error)) *OrderService_CancelOrderByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *OrderService) CreateOrder(ctx context.Context, order model.CreateOrderRequest) (model.OrderDTO, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 model.OrderDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) (model.OrderDTO, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrderRequest) model.OrderDTO); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Get(0).(model.OrderDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateOrderRequest) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.CreateOrderRequest
func (_e *OrderService_Expecter) CreateOrder(ctx interface{}, order interface{}) *OrderService_CreateOrder_Call {
	return &OrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *OrderService_CreateOrder_Call) Run(run func(ctx context.Context, order model.CreateOrderRequest)) *OrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateOrderRequest))
	})
	return _c
}

func (_c *OrderService_CreateOrder_Call) Return(_a0 model.OrderDTO, _a1 error) *OrderService_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_CreateOrder_Call) RunAndReturn(run func(context.Context, model.CreateOrderRequest) (model.OrderDTO, error)) *OrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByUUID provides a mock function with given fields: ctx, orderUUID
func (_m *OrderService) GetOrderByUUID(ctx context.Context, orderUUID string) (model.OrderDTO, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByUUID")
	}

	var r0 model.OrderDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.OrderDTO, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.OrderDTO); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(model.OrderDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_GetOrderByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByUUID'
type OrderService_GetOrderByUUID_Call struct {
	*mock.Call
}

// GetOrderByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *OrderService_Expecter) GetOrderByUUID(ctx interface{}, orderUUID interface{}) *OrderService_GetOrderByUUID_Call {
	return &OrderService_GetOrderByUUID_Call{Call: _e.mock.On("GetOrderByUUID", ctx, orderUUID)}
}

func (_c *OrderService_GetOrderByUUID_Call) Run(run func(ctx context.Context, orderUUID string)) *OrderService_GetOrderByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_GetOrderByUUID_Call) Return(_a0 model.OrderDTO, _a1 error) *OrderService_GetOrderByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_GetOrderByUUID_Call) RunAndReturn(run func(context.Context, string) (model.OrderDTO, error)) *OrderService_GetOrderByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function with given fields: ctx, paymentMethod, orderUUID
func (_m *OrderService) PayOrder(ctx context.Context, paymentMethod string, orderUUID string) (string, error) {
	ret := _m.Called(ctx, paymentMethod, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, paymentMethod, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, paymentMethod, orderUUID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, paymentMethod, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentMethod string
//   - orderUUID string
func (_e *OrderService_Expecter) PayOrder(ctx interface{}, paymentMethod interface{}, orderUUID interface{}) *OrderService_PayOrder_Call {
	return &OrderService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, paymentMethod, orderUUID)}
}

func (_c *OrderService_PayOrder_Call) Run(run func(ctx context.Context, paymentMethod string, orderUUID string)) *OrderService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *OrderService_PayOrder_Call) Return(_a0 string, _a1 error) *OrderService_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_PayOrder_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *OrderService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
